apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pdf-oidc
  namespace: pdf
spec:
  encryptedData:
    clientSecret: AgCpbMubVWqRk6lhhCoucnvFudjMxCJVRhM0zWVaA0q6Wx9LxCl8+1k6Iyt5ctpFf2Y9EvTV18mWfGwbNl9BPvoarZ/ZM1llOJ6MPGQo2YhaLLVRVn7OVPYTdwmFL3c40m/ywPEWkLSeyABpoDRSTEVDZyKcu1v62uoD1RTuYJFl6qZlw2loyg2fEW07KMCLbNtsVUUNrAl8SSQHyIVlq4D+ZV7dbdRnjxfUhWG/U/HS673mWYTBDPPBLChnRhGr+X5Nk87tWNt6kDnJ867XhgwUAioQAlN72KoRtTw5IMEHwv7abZgibs+Mg7+hxjAjoY4UcGs5lG9z0jWWi+sI7yunZjlXwRKYCAcDFJZCCyDvuwWKxg46glQZKJAwGuS6tNv9Q58ffcgA9peGSkH4DyjpRie6KLejqHVX1YVm7C72CCBkhnFNq1ky4C9w2HBZNRpMFejvN7EQd4O4dtm5k2diu3cVJShI8fDiPmV64rxVOQ27i0DVABm+6/HhZsbp8ViuNNOHGjmERZD3LaXzqirDw54mEck3Pnl6p+EcFvoquNPfz4t/1mvvPKjVtiXPgwf0dBNqfmGeC6jrgVZU7IDTq1mTCsBT+gzs/R5sx2ESNQFitp89+Q/1qyYcwWS7DKC4QiUhCwi6DS6mYCJGZo1XQFtGrddJzAOQKIGAicEQTwVr/PKO7Dzycxr+CMQFTgDETpcS6f3FgxQQczVeitaJQe5wuouvhAA7tUAOIxCYAvqOTjHoO8xyfGSlTTuta9I0NqR5ReB4Becqu8HwGWwOnMKHeSKkr59RhiG1R/CiXAW91lFnJw==
    cookieSecret: AgCPOFYByRP5nhbEVurpnRuOLPhMvT/m60Abjb3VCE5hxqm0jfDnMOLiAzIW4nCV+7OqZEug1eASgVhQ8nxKigxot85l6oK5APEFPjt0X1VmvE2mg31QKo90du1m14iuNc3UKlTLHjJ1q5dZb0Bggo0mYm/WZBzyC5/Y/2mKUkMuHsa0oxjSTJsucAqs1bq2pl3JcPViNghvyBwGscPXfPe4GRvLGEvtM8GUokRfPvTBrQ8InFVqBt6BSjWsDM1MQHpMeoGYlYmljQGCdIn9Bnz3AxNLG7q/SXAg0xcDynJdxgJuq24MoMMFjD/Lmsh+uWP6PnZ1NmtbWqUuK4uDhV45zdbEmYnktrrpGBPsZeIVLcryJjvHVB4NyFnpnD1D8zZmjUL6ur6GL6LAcdVHxr91anEfTbktEDlIAZHUWIWxngQh3AY3Hy6sGN+me4nswjYyLqwhfqmIvDO1o1z5THkhcPkK4cR34pOeD1zL6lFXllS3xKrJuL2xMNSL9p1gi/HbUp2QqBoLF4IGNPxmjOPWx9PrPvfNG7Hg0c0yVB6w9kSzG6Jy+EfyPAghuLYYfEWeX7pEe6nUvCPUjL6OUiw7SViu13ggKYUw2tq8xLG7kda+RvQZ9+l5t9DC2LLvRcvHMOT2zF3ifLanSkiWSeZUIe1qBwp5lGBF71JQ7PSTEEMOJ6OzshKvj33LE4sC90s3kq0LDCgLItusSXwiMaaPfQ92ucbf6MHy3t9dJFXscA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pdf-oidc
      namespace: pdf

