apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pdf-auth-secrets
  namespace: pdf
spec:
  encryptedData:
    password-hash: AgB5xeNV/dKuMMngceCFKHLR3+ttsLMtlzSPfnLSpYyydvfZGEzoK3G5hY8RouowSBSDPc182RYCVSl2BzQ0LUVYFtVI9dXuG0k7mJuSYV0HtWRZSQoQmf+D2ElBx6i0t632NXPR0L+Y1474g8drcOy3dwcDMj51ZNvtE9lVghH9h8FphlhVigrMfj/xry08YKBK5PPIzn3cSbZwyt5H/JU7hhBMib6f+m7NweG/ocKypBeLrgkD2yK2X63VzAvfjqXIgDtvJQar4vBsoBqKPrFwV+dAS63D/camPNMMOuqB9XL5RrcOmrtgZCYAjneD3j1PaIQ0eGOlD3x1LiyDLfaxdIP2qM1VkrL9vc8lRrr5gKZhELX1uT4vzQQt8+XJhChV9nqUNyrbTxuAtea0xPMacxaRYp7MJSsPIM0u8Go/8ZHVhrxmk9VZoiLqAi0RLjVZU++2b1ejGz+krLDPDftNCXI2e1ijhofQXahePCYTh0ykVLiFvhnsuSOq0YrvVDMlHLK7wPGYAB2UVcZNBWUKsHyInTakVfEq8qb0pmeWrOMbwNDe6EbKlgnnaYYrSUo5vVwLZaue4HuJuqjaoMYhmh0m/Klv2lXLrmnps8l4oKLF89OhmBcYnYeUBvcAtlUgDrxdHHotaH4mspIklM4NVpxINKzC6lQwkf+32pu5W7B8s6otm5jGV1a0NvOGBI15KGue/i19JQK2H0RJoeg+yGQJltpTxvnHyQzD4FmncxmUKJjoJ4hgg8xFOJFuZhT2DbERSi/E18yMYKM=
    username: AgCwkcjajNzkvffrCAF01xxXevz9L+uPscofHvdol1/6EAUwZreJPIMIJSQoKgX4IWYXZAZ4PWuoFlacgv72fQ4nT5xHast8W645QrahqTCt7OLU9d9jnxuBa3dWqsfEc8xrgn3LQoWCmmrxyhWD7EyXyr4/eTG651LCU+bYIWBmIf4bzuViRpenq3HbR1M7ip3rkyWl4AHcpxdzov7fLzjXd3UPkgijEWPJr5Rn89uSWPcZpimAH+/ZwwY5pbBm+a2LTbHhFDY46qcFpjEDdMioNvQjbmaZJi0fLQnh2uMSmVXPc4lGGWVpxEDHd+LBwnoikSWoSZyD4EtGWResxD6Wyg1QmjUWu+Iz7/aFvMTNG7a4aKwc6IerdGg53q54tliGzeWfrhhfoYv9NZA9U11RMHy7bh0EieONkLkBvfcRudjzAM2nFzf6NpZyRIwAoqGOph5/sBlpPteRZPdZCrcfxzRrGF/ZNA3PHehkTsU6HzYCoiDLiqCCvjfp4Kj+cfu4mjF1q33prB6DMqI+9F8hJ9utNJySExszKeDgUMGKJpbNF5SRJijE8oAdWPSQPo2pokhyJaoO9dvS2o2OMai9V5U9KgdCJldkd3qlaR5O8I3QF0ixLQaeVuUlkRYZmCwKx8B1jyy69ehxj9PiNfU+iFnodahCjv6rucInAMM+3WCrYfJAL/OcutEtP/NolRN3Nkg5nfHebeyytWih
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pdf-auth-secrets
      namespace: pdf
    type: Opaque

